spring:
  application:
    name: todo-list

  datasource:
    url: jdbc:h2:mem:todolistdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

server:
  port: 8083

cors:
  allowed:
    origins: http://localhost:4200
